version: "3.8"

services:
    app:
        build: .
        environment:
            DATABASE_URL: postgresql://postgres:123@postgres:5432/books
            JWT_SECRET: secret
            PORT: 3001
        ports:
            - "3001:3001"
        depends_on:
            - postgres
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: books
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres-data:
